spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true # true 설정시 JPA 쿼리문 확인 가능
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    web: INFO
    com: INFO
    root: INFO