apiVersion: v1
kind: Service
metadata:
  name: front-vue-lb
spec:
  type: LoadBalancer
  ports:
    - port: 30000
      targetPort: 3000
      protocol: TCP
  selector:
    app: front-vue
    tier: frontend
